name: goreleaser

on:
  workflow_call:
    secrets:
      GPG_PRIVATE_KEY:
        required: true
      GPG_PASSWORD:
        required: true
      GORELEASER_KEY:
        required: true
      FURY_TOKEN:
        required: true
      AUR_KEY:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
    - 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - 
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    -
      name: install deps
      run: sudo apt-get install -y upx make
    - 
      uses: actions/cache@v3
      with:
        path: |
            ~/.cache/go-build
            ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    -
      name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSWORD }}
    -
      uses: docker/setup-qemu-action@v1
    - 
      uses: docker/setup-buildx-action@v1
    - 
      uses: docker/login-action@v1
      name: ghcr.io login
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -  
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        distribution: goreleaser-pro
        args: release --rm-dist
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          AUR_KEY: ${{ secrets.AUR_KEY }}